apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: feed
    version: v2
  name: feed
spec:
  replicas: 2
  template: 
    metadata: 
      labels:
        service: feed
        version: v2
    spec:
      containers:
      - image: akapula/udacity-restapi-feed
        name: feed
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      restartPolicy: Always      